---
AWSTemplateFormatVersion: '2010-09-09'
Description: Cloud9 + QuickStart VPC (qs-1pb4pob92) (Please do not remove) May,29,2019
Metadata:
  LICENSE: Apache License, Version 2.0 
  AWS::CloudFormation::Interface:
    ParameterGroups:
    - Label:
        default: Cloud9 Configuration
      Parameters:
      - C9InstanceType
      - C9StopTime
      - C9Subnet
      - EBSVolumeSize           
    - Label:
        default: AWS Quick Start Configuration
      Parameters:
        - QSS3BucketName
        - QSS3KeyPrefix         
    ParameterLabels:
      C9InstanceType:
        default: Cloud9 instance type
      C9StopTime:
        default: Stop time
      C9Subnet:
        default: Private Subnet ID
      EBSVolumeSize:
        default: EBS volume size        
      QSS3BucketName:
        default: Quick Start S3 bucket name
      QSS3KeyPrefix:
        default: Quick Start S3 key prefix               
Parameters:
  QSS3BucketName:
    AllowedPattern: '^[0-9a-zA-Z]+([0-9a-zA-Z-]*[0-9a-zA-Z])*$'
    ConstraintDescription: >-
      Quick Start bucket name can include numbers, lowercase letters, uppercase
      letters, and hyphens (-). It cannot start or end with a hyphen (-).
    Default: aws-quickstart
    Description: >-
      S3 bucket name for the Quick Start assets. This string can include
      numbers, lowercase letters, uppercase letters, and hyphens (-). It cannot
      start or end with a hyphen (-).
    Type: String
  QSS3KeyPrefix:
    AllowedPattern: '^[0-9a-zA-Z-/]*$'
    ConstraintDescription: >-
      Quick Start key prefix can include numbers, lowercase letters, uppercase
      letters, hyphens (-), and forward slash (/).
    Default: quickstart-cloud9-ide/
    Description: >-
      S3 key prefix for the Quick Start assets. Quick Start key prefix can
      include numbers, lowercase letters, uppercase letters, hyphens (-), and
      forward slash (/).
    Type: String
  C9InstanceType:
    Description: The instance type of the new Amazon EC2 instance that AWS Cloud9
      will launch for the development environment.
    Type: String
    Default: t2.micro
    AllowedValues:
    - t2.micro
    - t2.small
    - m4.large
    - t2.nano
    - c4.large
    - t2.medium
    - t2.large
    - m4.xlarge
    - t2.xlarge
    - c4.xlarge
    - c4.2xlarge
    - m4.2xlarge
    - t2.2xlarge
    - c4.4xlarge
    - m4.4xlarge
    - c4.8xlarge
    - m4.10xlarge
    - m4.16xlarge
  C9StopTime:
    Description: The number of minutes until the running instance is shut down after
      the environment has last been used.
    Type: Number
    Default: 30
  C9Subnet:
    Description: The ID of the private subnet where your Cloud9 IDE will be installed.
    Type: String
  EBSVolumeSize:
    Description: The desired size (in GB) of the Amazon EBS volume for your Cloud9 IDE.
    Type: Number
    Default: 100        
Resources:
  C9Instance:
    Type: AWS::Cloud9::EnvironmentEC2
    Properties:
      Name: !Ref 'AWS::StackName'
      Description: !Sub '${AWS::AccountId}-${AWS::Region}-${AWS::StackName}'
      AutomaticStopTimeMinutes: !Ref 'C9StopTime'
      InstanceType: !Ref 'C9InstanceType'
      SubnetId: !Ref 'C9Subnet'
  C9Role:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service: ec2.amazonaws.com
          Action: sts:AssumeRole
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/AdministratorAccess
  C9InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    DependsOn: 'C9Instance'
    Properties:
      Path: /
      Roles: 
        - !Ref C9Role
  CRStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub >-
        https://${QSS3BucketName}.s3.amazonaws.com/${QSS3KeyPrefix}templates/cloud9-ide-cr.yaml
      Parameters:
        QSS3BucketName: !Ref 'QSS3BucketName'
        QSS3KeyPrefix: !Ref 'QSS3KeyPrefix'
        EBSVolumeSize: !Ref 'EBSVolumeSize'
        EnvironmentId: !Ref 'C9Instance'
        C9InstanceProfileName: !Ref 'C9InstanceProfile'
        C9InstanceProfileArn: !GetAtt 'C9InstanceProfile.Arn'
        IDEStackName: !Ref 'AWS::StackName'
Outputs:
  C9Instance:
    Description: Cloud9 Instance Name
    Value: !Ref 'C9Instance'
  C9InstanceProfileName:
    Description: Cloud9 Instance Profile Name
    Value: !Ref 'C9InstanceProfile'
  C9InstanceProfileArn:
    Description: Cloud9 Instance Profile Arn
    Value: !GetAtt 'C9InstanceProfile.Arn'
  IDEStackName:
    Description: CloudFormation Stack Name
    Value: !Ref 'AWS::StackName'
